#!/bin/bash

echo "
CONDOR_HOST = $CONDOR_HOST
DAEMON_LIST = MASTER, STARTD
DISCARD_SESSION_KEYRING_ON_STARTUP = False
DISCARD_SESSION_KEYRING_ON_STARTUP=False
TRUST_UID_DOMAIN=true

ALLOW_ADMINISTRATOR = \$(CONDOR_HOST)
ALLOW_OWNER = \$(FULL_HOSTNAME), \$(ALLOW_ADMINISTRATOR)
ALLOW_READ = *
ALLOW_WRITE = *
ALLOW_CLIENT = *
SCHED_NAME = $CONDOR_HOST
" > /etc/condor/condor_config.local

/usr/sbin/condor_master -pidfile /var/run/condor/condor.pid -f -t
